# required
token: xoxp-foo-blah-etc  # token from https://api.slack.com/web

# optional (with defaults shown)
username: nimbus          # name of bot
icon_emoji: cloud         # bot icon
polling_interval: 1       # how often (in seconds) to check for new events
command_prefix: '!'       # commands are prefixed with this character (ie !help)
debug_mode: False         # If true, logs all processed events
future_workers: 15        # Number of workers for concurrent processing of commands
